# Dedicated NooHub-only MQTT broker for SprutHub.
# Install to:
# /etc/mosquitto/noohub_spruthub_mosquitto.conf
#
# SprutHub MQTT controller can connect to the Wiren Board IP:
# <wirenboard-ip>:45883

listener 45883 0.0.0.0
allow_anonymous true
persistence false
log_dest syslog
